name: CI Build

on: 
  pull_request:
    branches: 
      - "features/**"

jobs:

  test:

    strategy:
      matrix:
        python: ['3.11', '3.12', '3.13']
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: python3 -m pip install --upgrade nox

      - name: Execute Tests
        run: python3 -m nox -s tests-${{matrix.python}}

      - name: Lint
        run: python -m nox -s lint